---
- hosts: db_server
  sudo: true
  user: vagrant
  tasks:
    - name: install packages PostgreSQL
      apt: name=postgresql update_cache=yes

    - name: install packages MySQL server
      apt: name=mysql-server update_cache=yes

    - name: install packages MySQL client
      apt: name=mysql-client update_cache=yes
