---
- hosts: db_server
  sudo: true
  user: vagrant
  tasks:
    - name: install packages
      apt: name={{item}} update_cache=yes
      with_items:
        - postgresql
        - libpq-dev
        - mysql-server
        - mysql-client
        - zsh
        - vim
        - htop
        - python3
        - ruby
        - redis-server
